debug-mode: false
# -------------------------------------------------- #
#
# Gizmo 1.2.0 - Made by Jeqo
#
# Discord:
# https://jeqo.net/discord
#
# Resource & Data Pack Guides:
# https://jeqo.net/guides
#
# -------------------------------------------------- #
background-color: '&0' # Minecraft color and hex code supported.

delay: 0 # The delay (in ticks) for the welcome screen to be displayed after joining.
delay-background: true # Display the background texture while the delay is active.

enable-fade: true # Fade the screen with your background texture when advancing.
fade-time: 10 # The duration (in ticks) for the fade.

player-command-on-advance: # Force the player to execute commands when advancing.
  enable: false
  commands: # Make sure to enter the command without a "/". Use a new line for each command.
    - 'msg Jeqo Gizmo is the best!'

console-command-on-advance: # Execute commands from console when the player advances.
  enable: false
  commands:
    - 'give %player% diamond 1'
    - 'playsound minecraft:ui.toast.in ambient %player% ~ ~ ~ 5 1'

# Give the player invulnerability when loading the pack.
# Recommended if you don't have a plugin that keeps your players safe whilst loading the pack.
player-invulnerable-during-load: true
blindness-during-prompt: true # Give players blindness when they have the pack prompt.

kick-on-decline: false # Kick the player if they don't accept the pack.

hide-join-messages: false # If true, player join messages will be hidden.
hide-quit-messages: false # If true, player quit messages will be hidden.

sound-on-pack-load: # Play a sound when the player's pack finishes loading.
  enable: true
  sound: ENTITY_PLAYER_LEVELUP
  volume: 0.5
  pitch: 1

sound-on-advance: # Play a sound when the player advances from the welcome screen.
  enable: true
  sound: ENTITY_CHICKEN_EGG
  volume: 0.5
  pitch: 1